# Generated by Django 4.0.4 on 2022-07-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_in_group',
            field=models.BooleanField(default=True),
        ),
    ]
