# Generated by Django 4.0.4 on 2022-08-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_subscription_is_in_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='status',
            field=models.CharField(blank=True, choices=[(1, 'come'), (2, 'not come'), (3, 'no reason')], max_length=20, null=True),
        ),
    ]
