# Generated by Django 4.0.4 on 2022-08-04 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_remove_operation_is_missed'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
