# Generated by Django 4.0.4 on 2022-08-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0007_operation_update_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_active_user',
            field=models.BooleanField(default=True),
        ),
    ]
