# Generated by Django 4.0.4 on 2022-07-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_class_is_delete_events_is_delete_group_is_delete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
