# Generated by Django 4.0.4 on 2022-07-29 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_module_bank_account_alter_module_bank_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='group',
            name='teachers_share',
        ),
    ]
