# Generated by Django 4.0.4 on 2022-08-02 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_group_teacher_remove_group_teachers_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='module',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='main.module'),
        ),
    ]
