# Generated by Django 4.0.4 on 2022-08-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
